### ISSUE TITLE
OSX error: dyld[2174]: Library not loaded: @rpath/libintl.9.dylib (Missing)

### ISSUE THREAD

**Issue by Babsky** [aferrero2707/gimp-plugins-collection#11]
After having issues with libX11.6.dylib, I now have this missing libintl.9.dylib problem. It's definitely not hiding anywhere! Any help please?
  
Referenced from: /Users/me/Library/Application Support/GIMP/2.10/plug-ins/gmic_gimp_qt
  Reason: tried: '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../Frameworks/libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../../../libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../../../../../Frameworks/libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/GMIC/lib/libintl.9.dylib' (no such file), '/Applications/GIMP-2.10.app/Contents/Resources/lib/libintl.9.dylib' (no such file), '/Applications/GIMP-2.10.app/Contents/Frameworks/libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../Frameworks/libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../../../libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/../../../../../Frameworks/libintl.9.dylib' (no such file), '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/GMIC/lib/libintl.9.dylib' (no such file), '/Applications/GIMP-2.10.app/Contents/Resources/lib/libintl.9.dylib' (no such file), '/Applications/GIMP-2.10.app/Contents/Frameworks/libintl.9.dylib' (no such file), '/usr/local/lib/libintl.9.dylib' (no such file), '/usr/lib/libintl.9.dylib' (no such file)
/Applications/GIMP-2.10.app/Contents/MacOS/gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/Users/me/Library/Application Support/GIMP/2.10/plug-ins/gmic_gimp_qt'

**Comment by tmaekawa-rh** [comment]
I ran into the same problem, but solved it with the following steps;
1) install gettext with brew `brew install gettext`
2) you can find libintl.8.dylib in /usr/local/lib
3) make symbolic link `ln -s libintl.8.dylib libintl.9.dylib`

Then my gimp-2.10 shows G'MIC-qt in its Filter menu.

**Comment by Babsky** [comment]
> 

I forgot all about this! 
I actually did
`brew update 
brew upgrade 
/opt/local/lib ls libintl*`
which then showed libintl.8 was installed, then I created a sym link.
The thing is, libintl.9 should really have been included in the package.
