### ISSUE TITLE
Plugins not activated in GIMP_AppImage-git-2.10.9-20190403-x86_64.AppImage

### ISSUE THREAD

**Issue by s7habo** [aferrero2707/gimp-plugins-collection#2]
Hi @aferrero2707 ,

Just testing your latest GIMP AppImage with separate plug-ins and cannot see any of them in GIMP filters menu.

When I start GIMP AppImage via terminal, here's the output:

[GIMP_output.txt](https://github.com/aferrero2707/gimp-plugins-collection/files/3044774/GIMP_output.txt)

Plugins have been successfully copied into:
`$HOME/.config/GIMP-AppImage/2.10/plug-ins`

![Plugins](https://user-images.githubusercontent.com/38165484/55576706-31eaa580-5712-11e9-9460-74a2700dac38.png)

and are executable.

My OS is Kubuntu 18.04.

**Comment by aferrero2707** [comment]
@s7habo I found what was wrong... the newest GIMP AppImages should work properly, as far as I could test. No need to re-download the plug-ins, just one of the following GIMP AppImages:
https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-release-2.10.8-x86_64.AppImage
https://github.com/aferrero2707/gimp-appimage/releases/download/continuous/GIMP_AppImage-git-2.10.9-20190404-x86_64.AppImage (or newer)

**Comment by s7habo** [comment]
> the newest GIMP AppImages should work properly

Confirmed! It works now. Thanks for quick fix and response!
